(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [
		{name:"300x600_atlas_P_", frames: [[0,0,80,53]]},
		{name:"300x600_atlas_NP_", frames: [[0,0,300,600]]},
		{name:"300x600_atlas_NP_2", frames: [[0,0,300,600]]}
];


// symbols:



(lib.bg_300x600 = function() {
	this.initialize(ss["300x600_atlas_NP_"]);
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.bg_300x600_2 = function() {
	this.initialize(ss["300x600_atlas_NP_2"]);
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.snow = function() {
	this.initialize(img.snow);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,930,600);


(lib.starbucks_un_the_go = function() {
	this.initialize(ss["300x600_atlas_P_"]);
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.Tween8 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#F50D05").s().p("AgWCVQgFgJgDgLIgEgaIgBgWIACgkIAFgkQgGAAgFgEQgFgDAAgHIABgFIAOgbIAOgcIABgJIACgJIADgVIAHgZQADgLAHgIQAGgJALAAQAHAAAGAEQAHAFAAAJIAAADQAAARgIAVQgIAXgLAVIgDATIgEASIgGAiIgEAhIgBAiIABAcQACAOAEAOIABADIAAABQAAAHgFAEQgDADgGAAQgKAAgGgJg");
	this.shape.setTransform(124.275,17.9);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#F50D05").s().p("AAACjIgGgBIgEgEIgCgHQAAgHAEgEQADgFAFgCQALgMAIgSQAHgRAFgUQAEgTACgVIADgoIAAgIIAAgFIgBgFIAAgIIgJALIgFAGIgEAFIgDADIgOALIgPAKIgSAIQgKAEgIAAQgQAAgGgKQgHgJAAgUQAAgNADgQIAJggIAMgeQAHgOAJgMQAJgLAJgHQAJgHAJAAIAMAAIALACIALAFIAKAMQAEAEAAAFQAAAHgGAFQgFAFgHAAIgHgCIgFgEIgDgDIgEgCIgHAEIgHAFQgSAQgJAZQgJAZgBAfIAAgBQAKgBANgJQANgIALgLQALgMAIgMQAJgNAAgKIgBgCIAAgCIAAgCIAAgEQAAgEAGgEQAGgFAIAAQAJAAAEAIQADAIAAAMIAFAqIACAnIgDAjIgGAoIgLAmQgGATgIAOQgIAOgKAJQgKAJgLAAg");
	this.shape_1.setTransform(108.125,29.625);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#F50D05").s().p("AgjBYQgMgFgIgKQgJgLgEgPQgEgPABgVQABgRAIgTQAIgTANgPQAMgPAQgJQAPgJASAAQAKAAAHAEQAHAEAEAHQAEAGABAIIABARQgBASgJAOQgJAOgOAJQgNALgOAGQgQAGgNACQADAPAHAGQAHAFAJAAIAPgCIAQgFIANgJQAGgFAEgGQACgFAGABQAGAAAFADQAFAEACAFQACAFgCAFQgHAKgKAIQgJAIgMAFQgLAFgLADQgLADgKAAQgOAAgLgFgAACg1QgIAFgIAJQgHAJgGALQgGALgDAKIATgFQAKgDAIgHQAJgGAGgIQAGgJABgLQABgHgBgCQgBgBAAAAQAAgBgBAAQAAAAgBgBQgBAAAAAAQgJAAgIAGg");
	this.shape_2.setTransform(91.217,22.975);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#F50D05").s().p("AhABUQgFgFAAgJIABgUIAEg/QADggAFgeQACgHAFgDQAEgEAGAAQAIAAAFAGQAGAFgCAJIgCAIIAAAEIgBACIgBAEQAHgKAJgJQAKgJALAAQALAAAHAHQAGAHAEAKIAFAVIAEASIAIAoQAFAUAIASQACAFgBAFIgDAHIgHAFIgIACIgIgCQgEgDgDgFIgeh1QgFAEgEAJIgJAUIgIAWIgHAYIgFAVIgEAPQgBAIgFAEQgFAEgGAAQgGAAgGgGg");
	this.shape_3.setTransform(74.33,23.075);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#F50D05").s().p("AguBkIgFgFIgCgGIgBgFQAAgGACgFQADgGAFgBQAEgBADABIAIABIAGAAIAIgDIANgEIAPgIIAOgLQAGgFABgGQAAgDgGgDIgLgFIgMgDIgEgBIgUgGQgMgDgKgGQgKgEgHgJQgIgJABgNQAAgQALgNQAKgMAPgJQAPgIAPgEQARgEALAAQAGAAAIADQAHADAAAIQAAAWgQAAIgHgCIgFgCQgJAAgKADIgRAIQgIAEgFAFQgFAGAAAFQAAAEAEADIAJAGIAMAFIALADIAYAIIAUAJQAJAEAFAHQAEAHAAAJQAAAQgKANQgLAMgPAJQgPAJgQAGIgfAIIgEACIgEAAQgEAAgCgCg");
	this.shape_4.setTransform(57.55,24.125);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#F50D05").s().p("AgWCVQgFgJgDgLIgEgaIgBgWIACgkIAFgkQgGAAgFgEQgFgDAAgHIABgFIAOgbIAOgcIABgJIACgJIADgVIAHgZQADgLAHgIQAGgJALAAQAHAAAGAEQAHAFAAAJIAAADQAAARgIAVQgIAXgLAVIgDATIgEASIgGAiIgEAhIgBAiIABAcQACAOAEAOIABADIAAABQAAAHgFAEQgDADgGAAQgKAAgGgJg");
	this.shape_5.setTransform(47.325,17.9);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#F50D05").s().p("AgjBYQgMgFgIgKQgJgLgEgPQgEgPABgVQABgRAIgTQAIgTANgPQAMgPAQgJQAPgJASAAQAKAAAHAEQAHAEAEAHQAEAGABAIIABARQgBASgJAOQgJAOgOAJQgNALgOAGQgQAGgNACQADAPAHAGQAHAFAJAAIAPgCIAQgFIANgJQAGgFAEgGQACgFAGABQAGAAAFADQAFAEACAFQACAFgCAFQgHAKgKAIQgJAIgMAFQgLAFgLADQgLADgKAAQgOAAgLgFgAACg1QgIAFgIAJQgHAJgGALQgGALgDAKIATgFQAKgDAIgHQAJgGAGgIQAGgJABgLQABgHgBgCQgBgBAAAAQAAgBgBAAQAAAAgBgBQgBAAAAAAQgJAAgIAGg");
	this.shape_6.setTransform(33.267,22.975);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#F50D05").s().p("AhABUQgFgFAAgJIABgUIAEg/QADggAFgeQACgHAFgDQAEgEAGAAQAIAAAFAGQAGAFgCAJIgCAIIAAAEIgBACIgBAEQAHgKAJgJQAKgJALAAQALAAAHAHQAGAHAEAKIAFAVIAEASIAIAoQAFAUAIASQACAFgBAFIgDAHIgHAFIgIACIgIgCQgEgDgDgFIgeh1QgFAEgEAJIgJAUIgIAWIgHAYIgFAVIgEAPQgBAIgFAEQgFAEgGAAQgGAAgGgGg");
	this.shape_7.setTransform(16.38,23.075);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#F50D05").s().p("AApBcQgEgFgEgHIgFgRIgEgTQgQAWgPALQgQAMgNAAQgKAAgGgGQgGgFgEgGQgFgIgBgJIgBgPQAAgQABgMIAHgVIAKgYQAHgOAKgOQAJgOALgKQANgLALAAQAJAAAGAHQAFAHAAAGQAAAJgEAEIgHAEIgHgBIgEAAQgFACgHAGQgQARgIAVQgJAUABAYQAAAJACAFQADAFACAAIAGgDIAOgKQAIgHAHgNQAJgNAGgSIAFgRIACgNQACgQADgIQADgHAMAAQAGAAAEAEQAEADAAAJIgCAPIgDANIgDAVIgBATQAAAUADAQQAFARAFAKIADAGIACAFQgBAJgFACQgHAEgFAAQgHAAgFgFg");
	this.shape_8.setTransform(-0.7,23.35);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#F50D05").s().p("AhMBwQgFgOAAgWIACgjIAEglIAIgsIAJgoIAKgeQAFgMADgCQAHgCAFABQAGABAEAEQAEAEABAFQACAGgCAFIgFAQIgEALIgEAJIgDAKIgDAOIgEAXIAHgEIAGgCIAagKIAUgHIAVgDQAEgBAEADQAEACACAFQACAEgBAGQgBAFgHAEIgHADIgKADQgQACgPAGIgfAKIASAIIAMAHIAVANIARALIAQANIASAOQAHAFAAAGQABAHgFAFQgEAGgGABQgGABgGgFIgOgLIgMgJIgHgGIgNgKIgQgKIgSgKIgRgJIgBAQIgBAPQAAALADANQADANgCAMIgFAHQgEADgLAAQgMAAgEgOg");
	this.shape_9.setTransform(-17.4975,20.4583);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#F50D05").s().p("AguBkIgFgFIgCgGIgBgFQAAgGACgFQADgGAFgBQAEgBADABIAIABIAGAAIAIgDIANgEIAPgIIAOgLQAGgFABgGQAAgDgGgDIgLgFIgMgDIgEgBIgUgGQgMgDgKgGQgKgEgHgJQgIgJABgNQAAgQALgNQAKgMAPgJQAPgIAPgEQARgEALAAQAGAAAIADQAHADAAAIQAAAWgQAAIgHgCIgFgCQgJAAgKADIgRAIQgIAEgFAFQgFAGAAAFQAAAEAEADIAJAGIAMAFIALADIAYAIIAUAJQAJAEAFAHQAEAHAAAJQAAAQgKANQgLAMgPAJQgPAJgQAGIgfAIIgEACIgEAAQgEAAgCgCg");
	this.shape_10.setTransform(-45.95,24.125);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#F50D05").s().p("AgLB8QgDAAgEgDQgEgEgCgIQgCgIAAgPIABgPIABgcIACgYIABgRIABgRIACgQQACgIADgEQAEgFAHAAQAHAAAGAGQAHAGAAAJIgBADIAAAFIgCAUIgDAbIgCAaIgBAVIAAAJIACAJIADAHIACAHQAAAJgHAFQgHAEgHAAgAgFhYQgHgHAAgNQAAgJAFgEQAFgDAJAAQAIAAAFAEQAHAEAAANQAAAMgHAEQgGAFgFgBQgHAAgHgFg");
	this.shape_11.setTransform(-58.45,19.35);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#F50D05").s().p("AgMCHQgFgBgCgJIgDgdIAAgdQAAglAEglIgmAHQgJABgGgEQgFgEAAgHQAAgEAEgEQADgEAIgCIAJgCIAKgCIACgBIABAAIAMgDIAPgFIAKgqIAOgqQACgFAFgDQAFgDAEAAQAHAAAGAFQAFAFgBAJQgNAggIAgIATgEIAQgBIAJACIAGAFQADADAAAEQgBAFgDAEIgBACIgBABQgGAEgGAAIgWAEIgUAGIAAAAIAAAAIgFArIgCAsIABAbIACAbQABAHgGAEQgGADgFAAg");
	this.shape_12.setTransform(-70.125,18.575);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#F50D05").s().p("AAqBcQgGgFgCgHIgGgRIgEgTQgQAWgPALQgQAMgNAAQgKAAgGgGQgHgFgDgGQgEgIgCgJIgCgPQAAgQACgMIAHgVIAKgYQAHgOAJgOQAKgOALgKQAMgLALAAQAKAAAGAHQAGAHgBAGQABAJgFAEIgIAEIgGgBIgEAAQgFACgHAGQgQARgIAVQgIAUAAAYQgBAJADAFQADAFACAAIAGgDIAOgKQAHgHAIgNQAJgNAGgSIAFgRIABgNQADgQADgIQADgHAMAAQAGAAAEAEQADADABAJIgBAPIgEANIgDAVIgBATQAAAUADAQQAFARAFAKIAEAGIABAFQAAAJgHACQgFAEgGAAQgHAAgEgFg");
	this.shape_13.setTransform(-85.55,23.35);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#F50D05").s().p("AguBiQgDgDgDgGQgCgGABgLIABgQIAAgRQAAgZgEgaQgEgagLgUQgCgDACgFQACgFAEgEQAEgEAGgCQAGgBAHAGQAGAEADAJIAGAcIABACIAAAEQAOgWARgTQASgTAYgLQAIgDAHADQAGADAEAGIABAJIgCAJQgCAFgGACIgDABIgDAAIgDABQgRAIgNANQgNANgJARQgHAPgEATQgEASAAAUIAAAPIgBAKIgCAKIgGAGQgDADgGAAQgIAAgHgFg");
	this.shape_14.setTransform(-99.175,22.3308);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#F50D05").s().p("AAACjIgGgBIgEgEIgCgHQAAgHAEgEQADgFAFgCQALgMAIgSQAHgRAFgUQAEgTACgVIADgoIAAgIIAAgFIgBgFIAAgIIgJALIgFAGIgEAFIgDADIgOALIgPAKIgSAIQgKAEgIAAQgQAAgGgKQgHgJAAgUQAAgNADgQIAJggIAMgeQAHgOAJgMQAJgLAJgHQAJgHAJAAIAMAAIALACIALAFIAKAMQAEAEAAAFQAAAHgGAFQgFAFgHAAIgHgCIgFgEIgDgDIgEgCIgHAEIgHAFQgSAQgJAZQgJAZgBAfIAAgBQAKgBANgJQANgIALgLQALgMAIgMQAJgNAAgKIgBgCIAAgCIAAgCIAAgEQAAgEAGgEQAGgFAIAAQAJAAAEAIQADAIAAAMIAFAqIACAnIgDAjIgGAoIgLAmQgGATgIAOQgIAOgKAJQgKAJgLAAg");
	this.shape_15.setTransform(-117.775,29.625);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#F50D05").s().p("AhABUQgFgFAAgJIABgUIAEg/QADggAFgeQACgHAFgDQAEgEAGAAQAIAAAFAGQAGAFgCAJIgCAIIAAAEIgBACIgBAEQAHgKAJgJQAKgJALAAQALAAAHAHQAGAHAEAKIAFAVIAEASIAIAoQAFAUAIASQACAFgBAFIgDAHIgHAFIgIACIgIgCQgEgDgDgFIgeh1QgFAEgEAJIgJAUIgIAWIgHAYIgFAVIgEAPQgBAIgFAEQgFAEgGAAQgGAAgGgGg");
	this.shape_16.setTransform(52.43,-19.925);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#F50D05").s().p("AgjBYQgMgFgIgKQgJgLgEgPQgEgPABgVQABgRAIgTQAIgTANgPQAMgPAQgJQAPgJASAAQAKAAAHAEQAHAEAEAHQAEAGABAIIABARQgBASgJAOQgJAOgOAJQgNALgOAGQgQAGgNACQADAPAHAGQAHAFAJAAIAPgCIAQgFIANgJQAGgFAEgGQACgFAGABQAGAAAFADQAFAEACAFQACAFgCAFQgHAKgKAIQgJAIgMAFQgLAFgLADQgLADgKAAQgOAAgLgFgAACg1QgIAFgIAJQgHAJgGALQgGALgDAKIATgFQAKgDAIgHQAJgGAGgIQAGgJABgLQABgHgBgCQgBgBAAAAQAAgBgBAAQAAAAgBgBQgBAAAAAAQgJAAgIAGg");
	this.shape_17.setTransform(35.817,-20.025);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#F50D05").s().p("AAqCHQgGgFgCgHIgGgRIgEgTQgQAWgPALQgQAMgNAAQgKAAgGgFQgHgFgDgHQgEgIgCgIIgCgQQAAgQACgLIAHgXIAKgYQAHgNAJgOQAKgOALgKQAMgKALAAQAKAAAGAHQAGAGgBAGQABAJgFAEIgIAEIgGAAIgEAAQgGABgFAGQgRAQgIAVQgIAVAAAZQgBAIADAFQADAFACAAIAGgCIAOgLQAIgHAHgNQAJgMAGgUIAFgQIABgNQACgQAEgHQAEgIALAAQAGAAAEAEQADADABAJIgBAPIgEANIgDAUIgBAUQAAAUADAQQAFARAFAKIAEAGIABAGQAAAIgHADQgGADgFAAQgHAAgEgFgAAKhEQgHgDgEgFQgFgFgDgHQgCgGAAgIQAAgJADgHQAEgHAFgFQAHgEAHgCIAOgDQAQAAAJALQAJALAAAOQABAMgHAKQgFAJgLAEQgIADgHAAQgJAAgHgDgAAWhyIgEACQgGAFgBAGQAAAGAEAEQADAEAEABIAEAAQAFAAAFgEQAEgEAAgGQAAgFgDgFQgCgEgGgBIgDAAg");
	this.shape_18.setTransform(7.7,-23.975);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#F50D05").s().p("AgPCdQgGgEgBgIIgGg4QgDgcAAgdIAAgFIAAgEIgFACIgCABIgEACIgHADQgEABgFgBIgIgFIgEgIQgBgFACgEQACgFAGgDIgBAAQARgIAPgEIADgdIAEggIAIggQAFgQAGgMQAFgMAJgIQAIgIALAAQANAAAJAIQAIAIAFALQAFALACANQABAMgBAKQgDAOgNAAQgHAAgGgFQgGgEABgKIAAgIIgBgLIgCgKQgCgEgDAAQgCAAgDAFIgGANIgEAPIgDAKQgEAQgCAPIgCAgIALgCIAJgBIAJAAIAJgBIALABQAFACACAEIAAgBQAFAIgEAIQgEAIgLABIgCABIgBAAIgUACIgUADIACA6IAFA7IAEAFIACAHQAAAGgEAFQgEAFgJABIgBABQgGAAgGgEg");
	this.shape_19.setTransform(-6.8042,-24.0472);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#F50D05").s().p("AAACjIgGgBIgEgEIgCgHQAAgHAEgEQADgFAFgCQALgMAIgSQAHgRAFgUQAEgTACgVIADgoIAAgIIAAgFIgBgFIAAgIIgJALIgFAGIgEAFIgDADIgOALIgPAKIgSAIQgKAEgIAAQgQAAgGgKQgHgJAAgUQAAgNADgQIAJggIAMgeQAHgOAJgMQAJgLAJgHQAJgHAJAAIAMAAIALACIALAFIAKAMQAEAEAAAFQAAAHgGAFQgFAFgHAAIgHgCIgFgEIgDgDIgEgCIgHAEIgHAFQgSAQgJAZQgJAZgBAfIAAgBQAKgBANgJQANgIALgLQALgMAIgMQAJgNAAgKIgBgCIAAgCIAAgCIAAgEQAAgEAGgEQAGgFAIAAQAJAAAEAIQADAIAAAMIAFAqIACAnIgDAjIgGAoIgLAmQgGATgIAOQgIAOgKAJQgKAJgLAAg");
	this.shape_20.setTransform(-35.175,-13.375);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#F50D05").s().p("AgoBOQgKgHgIgMQgHgLgDgOQgEgPAAgNQAAgPAEgOQAFgNAHgLQAHgKAKgGQAKgGALAAIAEAAIAXgLQALgEAJAAQALAAAJAFQAIAEAFAIQAFAIADAJQADAJAAAKQAAARgHAUQgIAUgMASQgMARgQAMQgQAMgQAAQgPAAgLgHgAgUgbQgCAEgEACIgJADIgDAPIAAALQAAATAGAMQAHAMAKAAQAKAAAJgHQAJgIAIgMQAIgLAEgNQAFgOAAgMQAAgJgEgHQgDgIgJAAIgMACIgKAEIgJAGIgIAFIAAAAIgBAAg");
	this.shape_21.setTransform(-52.425,-19.725);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-132.9,-44,265.8,88);


(lib.Tween7 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#F50D05").s().p("AgWCVQgFgJgDgLIgEgaIgBgWIACgkIAFgkQgGAAgFgEQgFgDAAgHIABgFIAOgbIAOgcIABgJIACgJIADgVIAHgZQADgLAHgIQAGgJALAAQAHAAAGAEQAHAFAAAJIAAADQAAARgIAVQgIAXgLAVIgDATIgEASIgGAiIgEAhIgBAiIABAcQACAOAEAOIABADIAAABQAAAHgFAEQgDADgGAAQgKAAgGgJg");
	this.shape.setTransform(124.275,17.9);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#F50D05").s().p("AAACjIgGgBIgEgEIgCgHQAAgHAEgEQADgFAFgCQALgMAIgSQAHgRAFgUQAEgTACgVIADgoIAAgIIAAgFIgBgFIAAgIIgJALIgFAGIgEAFIgDADIgOALIgPAKIgSAIQgKAEgIAAQgQAAgGgKQgHgJAAgUQAAgNADgQIAJggIAMgeQAHgOAJgMQAJgLAJgHQAJgHAJAAIAMAAIALACIALAFIAKAMQAEAEAAAFQAAAHgGAFQgFAFgHAAIgHgCIgFgEIgDgDIgEgCIgHAEIgHAFQgSAQgJAZQgJAZgBAfIAAgBQAKgBANgJQANgIALgLQALgMAIgMQAJgNAAgKIgBgCIAAgCIAAgCIAAgEQAAgEAGgEQAGgFAIAAQAJAAAEAIQADAIAAAMIAFAqIACAnIgDAjIgGAoIgLAmQgGATgIAOQgIAOgKAJQgKAJgLAAg");
	this.shape_1.setTransform(108.125,29.625);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#F50D05").s().p("AgjBYQgMgFgIgKQgJgLgEgPQgEgPABgVQABgRAIgTQAIgTANgPQAMgPAQgJQAPgJASAAQAKAAAHAEQAHAEAEAHQAEAGABAIIABARQgBASgJAOQgJAOgOAJQgNALgOAGQgQAGgNACQADAPAHAGQAHAFAJAAIAPgCIAQgFIANgJQAGgFAEgGQACgFAGABQAGAAAFADQAFAEACAFQACAFgCAFQgHAKgKAIQgJAIgMAFQgLAFgLADQgLADgKAAQgOAAgLgFgAACg1QgIAFgIAJQgHAJgGALQgGALgDAKIATgFQAKgDAIgHQAJgGAGgIQAGgJABgLQABgHgBgCQgBgBAAAAQAAgBgBAAQAAAAgBgBQgBAAAAAAQgJAAgIAGg");
	this.shape_2.setTransform(91.217,22.975);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#F50D05").s().p("AhABUQgFgFAAgJIABgUIAEg/QADggAFgeQACgHAFgDQAEgEAGAAQAIAAAFAGQAGAFgCAJIgCAIIAAAEIgBACIgBAEQAHgKAJgJQAKgJALAAQALAAAHAHQAGAHAEAKIAFAVIAEASIAIAoQAFAUAIASQACAFgBAFIgDAHIgHAFIgIACIgIgCQgEgDgDgFIgeh1QgFAEgEAJIgJAUIgIAWIgHAYIgFAVIgEAPQgBAIgFAEQgFAEgGAAQgGAAgGgGg");
	this.shape_3.setTransform(74.33,23.075);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#F50D05").s().p("AguBkIgFgFIgCgGIgBgFQAAgGACgFQADgGAFgBQAEgBADABIAIABIAGAAIAIgDIANgEIAPgIIAOgLQAGgFABgGQAAgDgGgDIgLgFIgMgDIgEgBIgUgGQgMgDgKgGQgKgEgHgJQgIgJABgNQAAgQALgNQAKgMAPgJQAPgIAPgEQARgEALAAQAGAAAIADQAHADAAAIQAAAWgQAAIgHgCIgFgCQgJAAgKADIgRAIQgIAEgFAFQgFAGAAAFQAAAEAEADIAJAGIAMAFIALADIAYAIIAUAJQAJAEAFAHQAEAHAAAJQAAAQgKANQgLAMgPAJQgPAJgQAGIgfAIIgEACIgEAAQgEAAgCgCg");
	this.shape_4.setTransform(57.55,24.125);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#F50D05").s().p("AgWCVQgFgJgDgLIgEgaIgBgWIACgkIAFgkQgGAAgFgEQgFgDAAgHIABgFIAOgbIAOgcIABgJIACgJIADgVIAHgZQADgLAHgIQAGgJALAAQAHAAAGAEQAHAFAAAJIAAADQAAARgIAVQgIAXgLAVIgDATIgEASIgGAiIgEAhIgBAiIABAcQACAOAEAOIABADIAAABQAAAHgFAEQgDADgGAAQgKAAgGgJg");
	this.shape_5.setTransform(47.325,17.9);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#F50D05").s().p("AgjBYQgMgFgIgKQgJgLgEgPQgEgPABgVQABgRAIgTQAIgTANgPQAMgPAQgJQAPgJASAAQAKAAAHAEQAHAEAEAHQAEAGABAIIABARQgBASgJAOQgJAOgOAJQgNALgOAGQgQAGgNACQADAPAHAGQAHAFAJAAIAPgCIAQgFIANgJQAGgFAEgGQACgFAGABQAGAAAFADQAFAEACAFQACAFgCAFQgHAKgKAIQgJAIgMAFQgLAFgLADQgLADgKAAQgOAAgLgFgAACg1QgIAFgIAJQgHAJgGALQgGALgDAKIATgFQAKgDAIgHQAJgGAGgIQAGgJABgLQABgHgBgCQgBgBAAAAQAAgBgBAAQAAAAgBgBQgBAAAAAAQgJAAgIAGg");
	this.shape_6.setTransform(33.267,22.975);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#F50D05").s().p("AhABUQgFgFAAgJIABgUIAEg/QADggAFgeQACgHAFgDQAEgEAGAAQAIAAAFAGQAGAFgCAJIgCAIIAAAEIgBACIgBAEQAHgKAJgJQAKgJALAAQALAAAHAHQAGAHAEAKIAFAVIAEASIAIAoQAFAUAIASQACAFgBAFIgDAHIgHAFIgIACIgIgCQgEgDgDgFIgeh1QgFAEgEAJIgJAUIgIAWIgHAYIgFAVIgEAPQgBAIgFAEQgFAEgGAAQgGAAgGgGg");
	this.shape_7.setTransform(16.38,23.075);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#F50D05").s().p("AApBcQgEgFgEgHIgFgRIgEgTQgQAWgPALQgQAMgNAAQgKAAgGgGQgGgFgEgGQgFgIgBgJIgBgPQAAgQABgMIAHgVIAKgYQAHgOAKgOQAJgOALgKQANgLALAAQAJAAAGAHQAFAHAAAGQAAAJgEAEIgHAEIgHgBIgEAAQgFACgHAGQgQARgIAVQgJAUABAYQAAAJACAFQADAFACAAIAGgDIAOgKQAIgHAHgNQAJgNAGgSIAFgRIACgNQACgQADgIQADgHAMAAQAGAAAEAEQAEADAAAJIgCAPIgDANIgDAVIgBATQAAAUADAQQAFARAFAKIADAGIACAFQgBAJgFACQgHAEgFAAQgHAAgFgFg");
	this.shape_8.setTransform(-0.7,23.35);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#F50D05").s().p("AhMBwQgFgOAAgWIACgjIAEglIAIgsIAJgoIAKgeQAFgMADgCQAHgCAFABQAGABAEAEQAEAEABAFQACAGgCAFIgFAQIgEALIgEAJIgDAKIgDAOIgEAXIAHgEIAGgCIAagKIAUgHIAVgDQAEgBAEADQAEACACAFQACAEgBAGQgBAFgHAEIgHADIgKADQgQACgPAGIgfAKIASAIIAMAHIAVANIARALIAQANIASAOQAHAFAAAGQABAHgFAFQgEAGgGABQgGABgGgFIgOgLIgMgJIgHgGIgNgKIgQgKIgSgKIgRgJIgBAQIgBAPQAAALADANQADANgCAMIgFAHQgEADgLAAQgMAAgEgOg");
	this.shape_9.setTransform(-17.4975,20.4583);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#F50D05").s().p("AguBkIgFgFIgCgGIgBgFQAAgGACgFQADgGAFgBQAEgBADABIAIABIAGAAIAIgDIANgEIAPgIIAOgLQAGgFABgGQAAgDgGgDIgLgFIgMgDIgEgBIgUgGQgMgDgKgGQgKgEgHgJQgIgJABgNQAAgQALgNQAKgMAPgJQAPgIAPgEQARgEALAAQAGAAAIADQAHADAAAIQAAAWgQAAIgHgCIgFgCQgJAAgKADIgRAIQgIAEgFAFQgFAGAAAFQAAAEAEADIAJAGIAMAFIALADIAYAIIAUAJQAJAEAFAHQAEAHAAAJQAAAQgKANQgLAMgPAJQgPAJgQAGIgfAIIgEACIgEAAQgEAAgCgCg");
	this.shape_10.setTransform(-45.95,24.125);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#F50D05").s().p("AgLB8QgDAAgEgDQgEgEgCgIQgCgIAAgPIABgPIABgcIACgYIABgRIABgRIACgQQACgIADgEQAEgFAHAAQAHAAAGAGQAHAGAAAJIgBADIAAAFIgCAUIgDAbIgCAaIgBAVIAAAJIACAJIADAHIACAHQAAAJgHAFQgHAEgHAAgAgFhYQgHgHAAgNQAAgJAFgEQAFgDAJAAQAIAAAFAEQAHAEAAANQAAAMgHAEQgGAFgFgBQgHAAgHgFg");
	this.shape_11.setTransform(-58.45,19.35);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#F50D05").s().p("AgMCHQgFgBgCgJIgDgdIAAgdQAAglAEglIgmAHQgJABgGgEQgFgEAAgHQAAgEAEgEQADgEAIgCIAJgCIAKgCIACgBIABAAIAMgDIAPgFIAKgqIAOgqQACgFAFgDQAFgDAEAAQAHAAAGAFQAFAFgBAJQgNAggIAgIATgEIAQgBIAJACIAGAFQADADAAAEQgBAFgDAEIgBACIgBABQgGAEgGAAIgWAEIgUAGIAAAAIAAAAIgFArIgCAsIABAbIACAbQABAHgGAEQgGADgFAAg");
	this.shape_12.setTransform(-70.125,18.575);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#F50D05").s().p("AAqBcQgGgFgCgHIgGgRIgEgTQgQAWgPALQgQAMgNAAQgKAAgGgGQgHgFgDgGQgEgIgCgJIgCgPQAAgQACgMIAHgVIAKgYQAHgOAJgOQAKgOALgKQAMgLALAAQAKAAAGAHQAGAHgBAGQABAJgFAEIgIAEIgGgBIgEAAQgFACgHAGQgQARgIAVQgIAUAAAYQgBAJADAFQADAFACAAIAGgDIAOgKQAHgHAIgNQAJgNAGgSIAFgRIABgNQADgQADgIQADgHAMAAQAGAAAEAEQADADABAJIgBAPIgEANIgDAVIgBATQAAAUADAQQAFARAFAKIAEAGIABAFQAAAJgHACQgFAEgGAAQgHAAgEgFg");
	this.shape_13.setTransform(-85.55,23.35);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#F50D05").s().p("AguBiQgDgDgDgGQgCgGABgLIABgQIAAgRQAAgZgEgaQgEgagLgUQgCgDACgFQACgFAEgEQAEgEAGgCQAGgBAHAGQAGAEADAJIAGAcIABACIAAAEQAOgWARgTQASgTAYgLQAIgDAHADQAGADAEAGIABAJIgCAJQgCAFgGACIgDABIgDAAIgDABQgRAIgNANQgNANgJARQgHAPgEATQgEASAAAUIAAAPIgBAKIgCAKIgGAGQgDADgGAAQgIAAgHgFg");
	this.shape_14.setTransform(-99.175,22.3308);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#F50D05").s().p("AAACjIgGgBIgEgEIgCgHQAAgHAEgEQADgFAFgCQALgMAIgSQAHgRAFgUQAEgTACgVIADgoIAAgIIAAgFIgBgFIAAgIIgJALIgFAGIgEAFIgDADIgOALIgPAKIgSAIQgKAEgIAAQgQAAgGgKQgHgJAAgUQAAgNADgQIAJggIAMgeQAHgOAJgMQAJgLAJgHQAJgHAJAAIAMAAIALACIALAFIAKAMQAEAEAAAFQAAAHgGAFQgFAFgHAAIgHgCIgFgEIgDgDIgEgCIgHAEIgHAFQgSAQgJAZQgJAZgBAfIAAgBQAKgBANgJQANgIALgLQALgMAIgMQAJgNAAgKIgBgCIAAgCIAAgCIAAgEQAAgEAGgEQAGgFAIAAQAJAAAEAIQADAIAAAMIAFAqIACAnIgDAjIgGAoIgLAmQgGATgIAOQgIAOgKAJQgKAJgLAAg");
	this.shape_15.setTransform(-117.775,29.625);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#F50D05").s().p("AhABUQgFgFAAgJIABgUIAEg/QADggAFgeQACgHAFgDQAEgEAGAAQAIAAAFAGQAGAFgCAJIgCAIIAAAEIgBACIgBAEQAHgKAJgJQAKgJALAAQALAAAHAHQAGAHAEAKIAFAVIAEASIAIAoQAFAUAIASQACAFgBAFIgDAHIgHAFIgIACIgIgCQgEgDgDgFIgeh1QgFAEgEAJIgJAUIgIAWIgHAYIgFAVIgEAPQgBAIgFAEQgFAEgGAAQgGAAgGgGg");
	this.shape_16.setTransform(52.43,-19.925);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#F50D05").s().p("AgjBYQgMgFgIgKQgJgLgEgPQgEgPABgVQABgRAIgTQAIgTANgPQAMgPAQgJQAPgJASAAQAKAAAHAEQAHAEAEAHQAEAGABAIIABARQgBASgJAOQgJAOgOAJQgNALgOAGQgQAGgNACQADAPAHAGQAHAFAJAAIAPgCIAQgFIANgJQAGgFAEgGQACgFAGABQAGAAAFADQAFAEACAFQACAFgCAFQgHAKgKAIQgJAIgMAFQgLAFgLADQgLADgKAAQgOAAgLgFgAACg1QgIAFgIAJQgHAJgGALQgGALgDAKIATgFQAKgDAIgHQAJgGAGgIQAGgJABgLQABgHgBgCQgBgBAAAAQAAgBgBAAQAAAAgBgBQgBAAAAAAQgJAAgIAGg");
	this.shape_17.setTransform(35.817,-20.025);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#F50D05").s().p("AAqCHQgGgFgCgHIgGgRIgEgTQgQAWgPALQgQAMgNAAQgKAAgGgFQgHgFgDgHQgEgIgCgIIgCgQQAAgQACgLIAHgXIAKgYQAHgNAJgOQAKgOALgKQAMgKALAAQAKAAAGAHQAGAGgBAGQABAJgFAEIgIAEIgGAAIgEAAQgGABgFAGQgRAQgIAVQgIAVAAAZQgBAIADAFQADAFACAAIAGgCIAOgLQAIgHAHgNQAJgMAGgUIAFgQIABgNQACgQAEgHQAEgIALAAQAGAAAEAEQADADABAJIgBAPIgEANIgDAUIgBAUQAAAUADAQQAFARAFAKIAEAGIABAGQAAAIgHADQgGADgFAAQgHAAgEgFgAAKhEQgHgDgEgFQgFgFgDgHQgCgGAAgIQAAgJADgHQAEgHAFgFQAHgEAHgCIAOgDQAQAAAJALQAJALAAAOQABAMgHAKQgFAJgLAEQgIADgHAAQgJAAgHgDgAAWhyIgEACQgGAFgBAGQAAAGAEAEQADAEAEABIAEAAQAFAAAFgEQAEgEAAgGQAAgFgDgFQgCgEgGgBIgDAAg");
	this.shape_18.setTransform(7.7,-23.975);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#F50D05").s().p("AgPCdQgGgEgBgIIgGg4QgDgcAAgdIAAgFIAAgEIgFACIgCABIgEACIgHADQgEABgFgBIgIgFIgEgIQgBgFACgEQACgFAGgDIgBAAQARgIAPgEIADgdIAEggIAIggQAFgQAGgMQAFgMAJgIQAIgIALAAQANAAAJAIQAIAIAFALQAFALACANQABAMgBAKQgDAOgNAAQgHAAgGgFQgGgEABgKIAAgIIgBgLIgCgKQgCgEgDAAQgCAAgDAFIgGANIgEAPIgDAKQgEAQgCAPIgCAgIALgCIAJgBIAJAAIAJgBIALABQAFACACAEIAAgBQAFAIgEAIQgEAIgLABIgCABIgBAAIgUACIgUADIACA6IAFA7IAEAFIACAHQAAAGgEAFQgEAFgJABIgBABQgGAAgGgEg");
	this.shape_19.setTransform(-6.8042,-24.0472);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#F50D05").s().p("AAACjIgGgBIgEgEIgCgHQAAgHAEgEQADgFAFgCQALgMAIgSQAHgRAFgUQAEgTACgVIADgoIAAgIIAAgFIgBgFIAAgIIgJALIgFAGIgEAFIgDADIgOALIgPAKIgSAIQgKAEgIAAQgQAAgGgKQgHgJAAgUQAAgNADgQIAJggIAMgeQAHgOAJgMQAJgLAJgHQAJgHAJAAIAMAAIALACIALAFIAKAMQAEAEAAAFQAAAHgGAFQgFAFgHAAIgHgCIgFgEIgDgDIgEgCIgHAEIgHAFQgSAQgJAZQgJAZgBAfIAAgBQAKgBANgJQANgIALgLQALgMAIgMQAJgNAAgKIgBgCIAAgCIAAgCIAAgEQAAgEAGgEQAGgFAIAAQAJAAAEAIQADAIAAAMIAFAqIACAnIgDAjIgGAoIgLAmQgGATgIAOQgIAOgKAJQgKAJgLAAg");
	this.shape_20.setTransform(-35.175,-13.375);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#F50D05").s().p("AgoBOQgKgHgIgMQgHgLgDgOQgEgPAAgNQAAgPAEgOQAFgNAHgLQAHgKAKgGQAKgGALAAIAEAAIAXgLQALgEAJAAQALAAAJAFQAIAEAFAIQAFAIADAJQADAJAAAKQAAARgHAUQgIAUgMASQgMARgQAMQgQAMgQAAQgPAAgLgHgAgUgbQgCAEgEACIgJADIgDAPIAAALQAAATAGAMQAHAMAKAAQAKAAAJgHQAJgIAIgMQAIgLAEgNQAFgOAAgMQAAgJgEgHQgDgIgJAAIgMACIgKAEIgJAGIgIAFIAAAAIgBAAg");
	this.shape_21.setTransform(-52.425,-19.725);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-132.9,-44,265.8,88);


(lib.Tween6 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Ag9BUQgUgdAAg1QAAg0AVgfQAWghAnAAQApAAAVAgQATAeAAA0QAAA1gTAeQgWAggoAAQgpAAgVgfgAgdAAQAAAoAIAQQAGAPAQAAQAPAAAGgPQAIgQgBgoQAAhGgbAAQgfAAAABGg");
	this.shape.setTransform(122.25,24.425);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("Ag9BUQgUgdAAg1QAAg0AVgfQAWghAnAAQApAAAVAgQATAeAAA0QAAA1gTAeQgVAggpAAQgpAAgVgfgAgdAAQAAAoAIAQQAGAPAQAAQAPAAAGgPQAIgQAAgoQAAhGgcAAQgfAAAABGg");
	this.shape_1.setTransform(104.05,24.425);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgQBMQgJgHAAgLQAAgLAIgHQAIgGAJAAQAKAAAIAGQAIAHAAALQAAALgJAHQgHAGgKAAQgJAAgHgGgAgQgnQgJgHAAgKQAAgMAIgHQAIgGAJAAQAKAAAIAGQAIAHAAALQAAALgJAHQgHAHgKAAQgJAAgHgHg");
	this.shape_2.setTransform(91.325,27.725);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("Ag5BjQgZgSAAghQAAgOAHgNQALgTAUgJQgMgGgIgNQgIgNAAgOQAAgdAWgRQAUgPAfAAQAfgBATAPQAVARAAAdQAAAOgJAOQgIALgMAIQAQAGALANQANAQAAARQAAAggaAUQgXASgiAAQgjAAgWgQgAggAuQAAAMAKAJQAJAJANAAQAPAAAIgIQAJgIAAgOQAAgMgMgLQgJgHgNgFQgeARAAASgAgQhEQgIAGAAAIQAAAJAJAJQAHAIAJAFQAWgPAAgOQAAgJgHgHQgGgGgKgBQgJAAgHAHg");
	this.shape_3.setTransform(78.425,24.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgnBQQgJAAAAgJIAAiIQAAgKAJAAIAaAAQAJAAABAHIAAAJQAIgLAIgEQAKgFANAAIAJABQAFABgBAHIgFAeQgBAFgEAAIgLgBQgRAAgLANIAABeQAAAJgJAAg");
	this.shape_4.setTransform(56.4091,27.525);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AhCBRIgJgHQgDgDAAgCQAAgCADgFIAJgKQgNgVAAgfQAAgjAVgXQAXgXAlAAQAYAAARAJIAJgJQAFgGAHAGIAJAIQADADAAADQAAACgCADIgIAJQAOAVAAAgQAAAlgVAWQgWAXglAAQgaAAgTgKIgIAJQgDAEgDAAQgDAAgEgEgAgRAoQAIAGAJAAQARAAAIgOQAHgMAAgUIgBgOgAgXgfQgJAMABATIAAAMIAvg1QgHgEgIAAQgQAAgIAOg");
	this.shape_5.setTransform(40.5,27.731);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgdB1QgJABAAgKIAAhxIgQAAQgFAAgCgCQgCgCAAgGIAAgOQAAgJAIABIARAAIAAgLQAAhEA7AAQAVgBARAJQAFABAAAGIgBAHIgDAQQgBAIgIgCQgMgFgKAAQgUAAAAAZIAAAPIAhAAQAHAAAAAGIAAATQAAAIgHgBIghAAIAABwQAAAKgJAAg");
	this.shape_6.setTransform(26.175,23.8);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("Ag3BHQgFgCAAgEIAAgEIAHgUQACgGADAAIAFABQAYAKASAAQARAAAAgLQgBgIgPgGIgbgKQgOgFgJgKQgKgNAAgQQAAgYAUgNQARgLAXAAQAcAAAXAKQAEACAAAEIgBADIgHAXQgBADgDAAIgFAAQgUgIgPAAQgGAAgFAEQgDACAAAEQAAAIALAEIAhANQAcALAAAeQAAAZgUAOQgSALgZAAQgaAAgbgLg");
	this.shape_7.setTransform(4.65,27.725);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAcBzQgKAAgEgIIgjhAIgBAAIAAA/QAAAJgIAAIgfAAQgJAAAAgJIAAjOQAAgJAIgBIAigEQAGAAAAAIIAAB/IABAAIAjg4QADgFAHAAIAjAAQAFAAAAAEQAAABAAAAQAAABAAABQAAAAgBABQAAAAAAABIgqA4IAvBPQADAEAAADQAAAEgHAAg");
	this.shape_8.setTransform(-9.725,24.075);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgsA+QgVgWAAglQAAgmAVgXQAXgXAkAAQAZAAAUAJQAFACgBAHIgGAXQAAAEgEAAIgEgBQgQgGgMAAQgTAAgJAMQgKALAAAUQAAAWAKAMQAJALAQAAQAPAAARgHIAEgBQADAAABAEIAHAaQAAADgFADQgVAJgcAAQgkAAgUgUg");
	this.shape_9.setTransform(-25.975,27.725);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AhJAXIAAheQAAgIAKAAIAdAAQAJAAAAAIIAABWQABAWASAAQARAAAOgMIAAhgQAAgIAKAAIAdAAQAJAAAAAIIAACIQAAALgKAAIgaAAQgHAAgBgHIgBgGQgWARgcAAQgzAAAAg5g");
	this.shape_10.setTransform(-42.6,27.975);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgOBwQgLgFgHgHIgBAJQgDAEgFAAIgZAAQgKAAABgKIAAjNQgBgIAJgCIAigEQAFAAAAAHIAABMQARgOAWAAQAYAAARAQQAYAWABAsQAAAkgSAWQgTAYgiAAQgJAAgLgFgAgcAEIAAA+QAOALAMAAQAcAAAAgqQAAgpgbAAQgNAAgOAKg");
	this.shape_11.setTransform(-60.4,24.275);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgnBQQgJAAAAgJIAAiIQAAgKAJAAIAaAAQAJAAABAHIAAAJQAIgLAIgEQAKgFANAAIAJABQAFABgBAHIgFAeQgBAFgEAAIgLgBQgRAAgLANIAABeQAAAJgJAAg");
	this.shape_12.setTransform(-74.9409,27.525);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AhDA7QgQgWAAgiQAAgnAWgYQAUgVAcAAQAaAAAMASIABgHQABgHAGAAIAdAAQAIAAAAAIIAABtQAAAGAFAAIACAAQAHAAAAAGIAAATQAAAHgIAAIgRAAQgYAAgGgOIgBAAQgHAHgNAGQgMAFgMAAQghAAgSgXgAgYgfQgJALAAAUQAAAsAdAAQAHAAAIgFQAHgEAEgFIAAg8QgMgLgNAAQgNAAgIAKg");
	this.shape_13.setTransform(-90.775,27.725);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgaBYQgHgIgCgMQgCgJAAgWIAAg8IgNAAQgGAAgCgDQgBgBAAgHIAAgOQAAgIAIAAIAOAAIAAgiQAAgHAKgBIAegEQAHAAAAAIIAAAmIAjAAQAHAAAAAHIAAASQAAAIgHAAIgjAAIAAA9QAAAOADAGQAEAHAKAAQAHAAANgEIAEgBQAEAAABAFIADAUIABADQAAAEgFADQgTAIgWAAQgcAAgMgPg");
	this.shape_14.setTransform(-106.55,25.675);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AhGBoQgGgCAAgEIABgGIAJgaQACgGAEAAIAGABQAZAKAZAAQAKAAAJgFQALgHAAgKQAAgOgUgJIgqgUQgogRAAgoQAAgdAZgSQAXgRAeAAQAhAAAeANQAHADAAAFIgBAEIgKAZQgDAGgEAAIgGgCQgWgKgVAAQgaAAAAAUQAAALAVAJIAkARQApASAAAnQAAAhgYAVQgWATghAAQgiAAgigMg");
	this.shape_15.setTransform(-122,24.425);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgQCPQgNAAAAgMIAAiwQAAgLANAAIAkAAQAMAAAAALIAACwQAAAMgMAAgAgVhYQgLgIAAgOQAAgPAKgJQAKgIANAAQANAAAJAIQAKAJAAAOQAAAOgKAJQgKAIgMAAQgNAAgJgIg");
	this.shape_16.setTransform(123.75,-19.175);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgyBnQgMAAAAgMIAAivQAAgMAMAAIAhAAQAMAAAAAIIABANQALgOAKgGQAMgHARAAIAMACQAGABgCAJIgGAmQgBAHgFAAIgOgBQgVAAgPAQIAAB5QAAAMgMAAg");
	this.shape_17.setTransform(111.565,-15.175);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AglCXQgMAAAAgNIAAiRIgUAAQgHAAgDgCQgCgCAAgJIAAgRQAAgLAKAAIAWAAIAAgNQAAhZBMAAQAbAAAVAKQAHADAAAGIgCAKIgDAWQgCAJgJgDQgRgFgMAAQgZAAAAAgIAAASIApAAQAKAAAAAIIAAAYQAAAJgKAAIgpAAIAACQQAAAOgMAAg");
	this.shape_18.setTransform(96.375,-19.95);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AhACHQgKgEAEgMIAHgXQADgLAKAEQAYAKAVAAQAZAAAKgNQAHgKAAgWIAAgOQgWASgZAAQgmAAgYgXQgagaAAgvQAAgsAYgfQAZghArAAQAOAAANAGQANAFAHALIABgJQAAgIALAAIAjAAQALAAAAALIAACrQAABqhkAAQggAAgfgMgAgThWQgOAOgBAfQABAcAOANQAIAIAOAAQAVAAANgOIAAhOQgOgNgRAAQgOAAgLALg");
	this.shape_19.setTransform(75.2,-10.625);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgTCTQgLAAAAgLIAAkJQAAgLAKgBIAqgFQAJAAAAALIAAEPQAAALgLAAg");
	this.shape_20.setTransform(58.575,-19.6);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AhWBLQgVgbAAgsQAAgzAcgeQAagbAkgBQAhAAAQAYIACgJQABgJAIABIAlAAQAKAAAAAJIAACNQAAAGAGAAIADAAQAJAAAAAJIAAAXQAAAKgKAAIgWAAQgeAAgJgTIgBAAQgIAKgRAHQgQAIgPAAQgqAAgYgfgAgfgpQgMAPAAAaQAAA4AmAAQAJAAALgHQAJgEAEgHIAAhOQgPgOgRABQgQgBgLANg");
	this.shape_21.setTransform(41.475,-14.9);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgLBkQgLAAgEgIIhJi1IgBgEQAAgGAJAAIAvAAQAKAAADAKIAaBUIAHAcIABAAIAIgcIAbhUQAEgKAMAAIAlAAQAKAAAAAHIgBAFIhKCyQgEAJgKAAg");
	this.shape_22.setTransform(19.125,-14.875);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AAsBnQgLAAAAgMIAAhtQAAgcgYAAQgWAAgTAQIAAB5QAAAMgLAAIgnAAQgLAAAAgLIAAiwQAAgMAMAAIAhAAQALAAABAJIABAIQAdgXAjAAQBBAAAABJIAAB4QAAAMgMAAg");
	this.shape_23.setTransform(-13.175,-15.175);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AhDBNQgdgcAAgxQAAgvAdgdQAegdAuAAQAoAAAYAbQAYAaAAA0IAAAFQAAAMgOAAIhyAAQADASAQALQANALAUAAQAZAAAagLIAFgBQAFAAACAGQAIAZAAAHQAAAFgIAEQgfAOgrAAQgwAAgdgdgAAlgVQAAgPgIgKQgIgLgQAAQgNAAgLALQgJAKgCAPIBDAAIAAAAg");
	this.shape_24.setTransform(-35.725,-14.925);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgTCPQgOgGgIgIIgDALQgCAFgIAAIgfAAQgMAAAAgNIAAkGQAAgMAKgBIArgGQAJAAgBAJIAABiQAWgSAcAAQAeAAAXAUQAfAdAAA4QAAAtgWAdQgZAfgsAAQgLAAgPgHgAgkAFIAABPQASAPAQAAQAkAAAAg2QAAg0gjAAQgRAAgSAMg");
	this.shape_25.setTransform(-67.7,-19.35);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AhVBoIgLgJQgFgEAAgCQAAgEAFgGIALgNQgRgaAAgoQAAgtAbgdQAdgeAvAAQAgAAAWAMIALgMQAHgIAIAIIALAKQAGAEAAAEQAAACgEAFIgLALQAUAbAAAqQAAAugbAdQgdAegvAAQgiAAgXgOIgMAMQgEAFgDAAQgEAAgFgFgAgWA0QAJAHANAAQAVAAALgSQAKgQAAgZIgCgSgAgfgoQgKAQAAAYIACAPIA7hDQgIgGgLAAQgVAAgLASg");
	this.shape_26.setTransform(-91.575,-14.9065);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AA2COQgPAAgIgMIhMhqIgBAAIAABqQAAAMgMAAIgpAAQgNAAAAgMIAAkFQAAgKANAAIApAAQAMAAAAAKIAAByIABAAIBIh0QAGgIAMAAIApAAQAIAAAAAGIgDAGIhVB+IBnCCQAEAFAAADQAAAHgHAAg");
	this.shape_27.setTransform(-115.325,-19.125);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-137.1,-44.6,274.29999999999995,89.2);


(lib.Tween5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Ag9BUQgUgdAAg1QAAg0AVgfQAWghAnAAQApAAAVAgQATAeAAA0QAAA1gTAeQgWAggoAAQgpAAgVgfgAgdAAQAAAoAIAQQAGAPAQAAQAPAAAGgPQAIgQgBgoQAAhGgbAAQgfAAAABGg");
	this.shape.setTransform(122.25,24.425);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("Ag9BUQgUgdAAg1QAAg0AVgfQAWghAnAAQApAAAVAgQATAeAAA0QAAA1gTAeQgVAggpAAQgpAAgVgfgAgdAAQAAAoAIAQQAGAPAQAAQAPAAAGgPQAIgQAAgoQAAhGgcAAQgfAAAABGg");
	this.shape_1.setTransform(104.05,24.425);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgQBMQgJgHAAgLQAAgLAIgHQAIgGAJAAQAKAAAIAGQAIAHAAALQAAALgJAHQgHAGgKAAQgJAAgHgGgAgQgnQgJgHAAgKQAAgMAIgHQAIgGAJAAQAKAAAIAGQAIAHAAALQAAALgJAHQgHAHgKAAQgJAAgHgHg");
	this.shape_2.setTransform(91.325,27.725);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("Ag5BjQgZgSAAghQAAgOAHgNQALgTAUgJQgMgGgIgNQgIgNAAgOQAAgdAWgRQAUgPAfAAQAfgBATAPQAVARAAAdQAAAOgJAOQgIALgMAIQAQAGALANQANAQAAARQAAAggaAUQgXASgiAAQgjAAgWgQgAggAuQAAAMAKAJQAJAJANAAQAPAAAIgIQAJgIAAgOQAAgMgMgLQgJgHgNgFQgeARAAASgAgQhEQgIAGAAAIQAAAJAJAJQAHAIAJAFQAWgPAAgOQAAgJgHgHQgGgGgKgBQgJAAgHAHg");
	this.shape_3.setTransform(78.425,24.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgnBQQgJAAAAgJIAAiIQAAgKAJAAIAaAAQAJAAABAHIAAAJQAIgLAIgEQAKgFANAAIAJABQAFABgBAHIgFAeQgBAFgEAAIgLgBQgRAAgLANIAABeQAAAJgJAAg");
	this.shape_4.setTransform(56.4091,27.525);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AhCBRIgJgHQgDgDAAgCQAAgCADgFIAJgKQgNgVAAgfQAAgjAVgXQAXgXAlAAQAYAAARAJIAJgJQAFgGAHAGIAJAIQADADAAADQAAACgCADIgIAJQAOAVAAAgQAAAlgVAWQgWAXglAAQgaAAgTgKIgIAJQgDAEgDAAQgDAAgEgEgAgRAoQAIAGAJAAQARAAAIgOQAHgMAAgUIgBgOgAgXgfQgJAMABATIAAAMIAvg1QgHgEgIAAQgQAAgIAOg");
	this.shape_5.setTransform(40.5,27.731);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgdB1QgJABAAgKIAAhxIgQAAQgFAAgCgCQgCgCAAgGIAAgOQAAgJAIABIARAAIAAgLQAAhEA7AAQAVgBARAJQAFABAAAGIgBAHIgDAQQgBAIgIgCQgMgFgKAAQgUAAAAAZIAAAPIAhAAQAHAAAAAGIAAATQAAAIgHgBIghAAIAABwQAAAKgJAAg");
	this.shape_6.setTransform(26.175,23.8);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("Ag3BHQgFgCAAgEIAAgEIAHgUQACgGADAAIAFABQAYAKASAAQARAAAAgLQgBgIgPgGIgbgKQgOgFgJgKQgKgNAAgQQAAgYAUgNQARgLAXAAQAcAAAXAKQAEACAAAEIgBADIgHAXQgBADgDAAIgFAAQgUgIgPAAQgGAAgFAEQgDACAAAEQAAAIALAEIAhANQAcALAAAeQAAAZgUAOQgSALgZAAQgaAAgbgLg");
	this.shape_7.setTransform(4.65,27.725);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAcBzQgKAAgEgIIgjhAIgBAAIAAA/QAAAJgIAAIgfAAQgJAAAAgJIAAjOQAAgJAIgBIAigEQAGAAAAAIIAAB/IABAAIAjg4QADgFAHAAIAjAAQAFAAAAAEQAAABAAAAQAAABAAABQAAAAgBABQAAAAAAABIgqA4IAvBPQADAEAAADQAAAEgHAAg");
	this.shape_8.setTransform(-9.725,24.075);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgsA+QgVgWAAglQAAgmAVgXQAXgXAkAAQAZAAAUAJQAFACgBAHIgGAXQAAAEgEAAIgEgBQgQgGgMAAQgTAAgJAMQgKALAAAUQAAAWAKAMQAJALAQAAQAPAAARgHIAEgBQADAAABAEIAHAaQAAADgFADQgVAJgcAAQgkAAgUgUg");
	this.shape_9.setTransform(-25.975,27.725);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AhJAXIAAheQAAgIAKAAIAdAAQAJAAAAAIIAABWQABAWASAAQARAAAOgMIAAhgQAAgIAKAAIAdAAQAJAAAAAIIAACIQAAALgKAAIgaAAQgHAAgBgHIgBgGQgWARgcAAQgzAAAAg5g");
	this.shape_10.setTransform(-42.6,27.975);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgOBwQgLgFgHgHIgBAJQgDAEgFAAIgZAAQgKAAABgKIAAjNQgBgIAJgCIAigEQAFAAAAAHIAABMQARgOAWAAQAYAAARAQQAYAWABAsQAAAkgSAWQgTAYgiAAQgJAAgLgFgAgcAEIAAA+QAOALAMAAQAcAAAAgqQAAgpgbAAQgNAAgOAKg");
	this.shape_11.setTransform(-60.4,24.275);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgnBQQgJAAAAgJIAAiIQAAgKAJAAIAaAAQAJAAABAHIAAAJQAIgLAIgEQAKgFANAAIAJABQAFABgBAHIgFAeQgBAFgEAAIgLgBQgRAAgLANIAABeQAAAJgJAAg");
	this.shape_12.setTransform(-74.9409,27.525);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AhDA7QgQgWAAgiQAAgnAWgYQAUgVAcAAQAaAAAMASIABgHQABgHAGAAIAdAAQAIAAAAAIIAABtQAAAGAFAAIACAAQAHAAAAAGIAAATQAAAHgIAAIgRAAQgYAAgGgOIgBAAQgHAHgNAGQgMAFgMAAQghAAgSgXgAgYgfQgJALAAAUQAAAsAdAAQAHAAAIgFQAHgEAEgFIAAg8QgMgLgNAAQgNAAgIAKg");
	this.shape_13.setTransform(-90.775,27.725);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgaBYQgHgIgCgMQgCgJAAgWIAAg8IgNAAQgGAAgCgDQgBgBAAgHIAAgOQAAgIAIAAIAOAAIAAgiQAAgHAKgBIAegEQAHAAAAAIIAAAmIAjAAQAHAAAAAHIAAASQAAAIgHAAIgjAAIAAA9QAAAOADAGQAEAHAKAAQAHAAANgEIAEgBQAEAAABAFIADAUIABADQAAAEgFADQgTAIgWAAQgcAAgMgPg");
	this.shape_14.setTransform(-106.55,25.675);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AhGBoQgGgCAAgEIABgGIAJgaQACgGAEAAIAGABQAZAKAZAAQAKAAAJgFQALgHAAgKQAAgOgUgJIgqgUQgogRAAgoQAAgdAZgSQAXgRAeAAQAhAAAeANQAHADAAAFIgBAEIgKAZQgDAGgEAAIgGgCQgWgKgVAAQgaAAAAAUQAAALAVAJIAkARQApASAAAnQAAAhgYAVQgWATghAAQgiAAgigMg");
	this.shape_15.setTransform(-122,24.425);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgQCPQgNAAAAgMIAAiwQAAgLANAAIAkAAQAMAAAAALIAACwQAAAMgMAAgAgVhYQgLgIAAgOQAAgPAKgJQAKgIANAAQANAAAJAIQAKAJAAAOQAAAOgKAJQgKAIgMAAQgNAAgJgIg");
	this.shape_16.setTransform(123.75,-19.175);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgyBnQgMAAAAgMIAAivQAAgMAMAAIAhAAQAMAAAAAIIABANQALgOAKgGQAMgHARAAIAMACQAGABgCAJIgGAmQgBAHgFAAIgOgBQgVAAgPAQIAAB5QAAAMgMAAg");
	this.shape_17.setTransform(111.565,-15.175);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AglCXQgMAAAAgNIAAiRIgUAAQgHAAgDgCQgCgCAAgJIAAgRQAAgLAKAAIAWAAIAAgNQAAhZBMAAQAbAAAVAKQAHADAAAGIgCAKIgDAWQgCAJgJgDQgRgFgMAAQgZAAAAAgIAAASIApAAQAKAAAAAIIAAAYQAAAJgKAAIgpAAIAACQQAAAOgMAAg");
	this.shape_18.setTransform(96.375,-19.95);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AhACHQgKgEAEgMIAHgXQADgLAKAEQAYAKAVAAQAZAAAKgNQAHgKAAgWIAAgOQgWASgZAAQgmAAgYgXQgagaAAgvQAAgsAYgfQAZghArAAQAOAAANAGQANAFAHALIABgJQAAgIALAAIAjAAQALAAAAALIAACrQAABqhkAAQggAAgfgMgAgThWQgOAOgBAfQABAcAOANQAIAIAOAAQAVAAANgOIAAhOQgOgNgRAAQgOAAgLALg");
	this.shape_19.setTransform(75.2,-10.625);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgTCTQgLAAAAgLIAAkJQAAgLAKgBIAqgFQAJAAAAALIAAEPQAAALgLAAg");
	this.shape_20.setTransform(58.575,-19.6);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AhWBLQgVgbAAgsQAAgzAcgeQAagbAkgBQAhAAAQAYIACgJQABgJAIABIAlAAQAKAAAAAJIAACNQAAAGAGAAIADAAQAJAAAAAJIAAAXQAAAKgKAAIgWAAQgeAAgJgTIgBAAQgIAKgRAHQgQAIgPAAQgqAAgYgfgAgfgpQgMAPAAAaQAAA4AmAAQAJAAALgHQAJgEAEgHIAAhOQgPgOgRABQgQgBgLANg");
	this.shape_21.setTransform(41.475,-14.9);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgLBkQgLAAgEgIIhJi1IgBgEQAAgGAJAAIAvAAQAKAAADAKIAaBUIAHAcIABAAIAIgcIAbhUQAEgKAMAAIAlAAQAKAAAAAHIgBAFIhKCyQgEAJgKAAg");
	this.shape_22.setTransform(19.125,-14.875);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AAsBnQgLAAAAgMIAAhtQAAgcgYAAQgWAAgTAQIAAB5QAAAMgLAAIgnAAQgLAAAAgLIAAiwQAAgMAMAAIAhAAQALAAABAJIABAIQAdgXAjAAQBBAAAABJIAAB4QAAAMgMAAg");
	this.shape_23.setTransform(-13.175,-15.175);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AhDBNQgdgcAAgxQAAgvAdgdQAegdAuAAQAoAAAYAbQAYAaAAA0IAAAFQAAAMgOAAIhyAAQADASAQALQANALAUAAQAZAAAagLIAFgBQAFAAACAGQAIAZAAAHQAAAFgIAEQgfAOgrAAQgwAAgdgdgAAlgVQAAgPgIgKQgIgLgQAAQgNAAgLALQgJAKgCAPIBDAAIAAAAg");
	this.shape_24.setTransform(-35.725,-14.925);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgTCPQgOgGgIgIIgDALQgCAFgIAAIgfAAQgMAAAAgNIAAkGQAAgMAKgBIArgGQAJAAgBAJIAABiQAWgSAcAAQAeAAAXAUQAfAdAAA4QAAAtgWAdQgZAfgsAAQgLAAgPgHgAgkAFIAABPQASAPAQAAQAkAAAAg2QAAg0gjAAQgRAAgSAMg");
	this.shape_25.setTransform(-67.7,-19.35);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AhVBoIgLgJQgFgEAAgCQAAgEAFgGIALgNQgRgaAAgoQAAgtAbgdQAdgeAvAAQAgAAAWAMIALgMQAHgIAIAIIALAKQAGAEAAAEQAAACgEAFIgLALQAUAbAAAqQAAAugbAdQgdAegvAAQgiAAgXgOIgMAMQgEAFgDAAQgEAAgFgFgAgWA0QAJAHANAAQAVAAALgSQAKgQAAgZIgCgSgAgfgoQgKAQAAAYIACAPIA7hDQgIgGgLAAQgVAAgLASg");
	this.shape_26.setTransform(-91.575,-14.9065);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AA2COQgPAAgIgMIhMhqIgBAAIAABqQAAAMgMAAIgpAAQgNAAAAgMIAAkFQAAgKANAAIApAAQAMAAAAAKIAAByIABAAIBIh0QAGgIAMAAIApAAQAIAAAAAGIgDAGIhVB+IBnCCQAEAFAAADQAAAHgHAAg");
	this.shape_27.setTransform(-115.325,-19.125);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-137.1,-44.6,274.29999999999995,89.2);


(lib.Tween4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.snow();
	this.instance.parent = this;
	this.instance.setTransform(-196.8,-610,0.6559,0.6559,0,-90,90);

	this.instance_1 = new lib.snow();
	this.instance_1.parent = this;
	this.instance_1.setTransform(-196.8,610.05,0.6559,0.6559,-90);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_1},{t:this.instance}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-196.8,-610,393.6,1220.1);


(lib.Tween3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.snow();
	this.instance.parent = this;
	this.instance.setTransform(-196.8,-610.05,0.6559,0.6559,0,-90,90);

	this.instance_1 = new lib.snow();
	this.instance_1.parent = this;
	this.instance_1.setTransform(-196.8,610,0.6559,0.6559,-90);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_1},{t:this.instance}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-196.8,-610,393.6,1220);


(lib.Arrow = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#F3161C").s().p("ACgA4QgFgBgDgFQgCgEABgFIANgsQhZArhqAAQg4AAg3gMQgcgGgVgHQgFgCgCgEQgCgFACgEQACgFAEgCQAFgCAFACQAsAOA/AGQB8ALBjgvIgqgJQgFAAgCgFQgDgEABgFQABgFAEgDQAEgDAFABIBZASIgZBVQgCAKgKAAg");
	this.shape.setTransform(0.0179,0.0107);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-19.9,-5.7,39.9,11.4);


(lib.Symbol1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1_copy_copy_copy_copy
	this.instance = new lib.Tween3("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(57.75,-924.25,1,1,0,0,180);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(240).to({_off:false},0).to({x:49.1,y:-314.25},240).wait(1));

	// Layer_1_copy_copy_copy
	this.instance_1 = new lib.Tween3("synched",0);
	this.instance_1.parent = this;
	this.instance_1.setTransform(50.25,-316,1,1,0,0,180);

	this.instance_2 = new lib.Tween4("synched",0);
	this.instance_2.parent = this;
	this.instance_2.setTransform(-49.15,899,1,1,0,0,180);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_1}]}).to({state:[{t:this.instance_2}]},480).wait(1));
	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({_off:true,x:-49.15,y:899},480).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-245.9,-1534.3,500.5,3043.3999999999996);


// stage content:
(lib._300x600HTML5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_78 = function() {
		var _this = this;
		/*
		Stop a Movie Clip/Video
		Stops the specified movie clip or video.
		*/
		_this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(78).call(this.frame_78).wait(1));

	// Snow
	this.instance = new lib.Symbol1();
	this.instance.parent = this;
	this.instance.setTransform(146.8,305);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(79));

	// Layer_2
	this.instance_1 = new lib.starbucks_un_the_go();
	this.instance_1.parent = this;
	this.instance_1.setTransform(6,542);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(79));

	// FlashAICB
	this.instance_2 = new lib.Arrow("synched",0);
	this.instance_2.parent = this;
	this.instance_2.setTransform(220.55,252.4,1.8802,1.9453,0,-104.9999,75.0002);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(51).to({_off:false},0).to({scaleX:2.88,scaleY:2.88,skewX:-105,skewY:74.9999,x:220.45,y:283.15,alpha:1},12).wait(15).to({startPosition:0},0).wait(1));

	// KØB
	this.instance_3 = new lib.Tween5("synched",0);
	this.instance_3.parent = this;
	this.instance_3.setTransform(148.45,-44.6);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.instance_4 = new lib.Tween6("synched",0);
	this.instance_4.parent = this;
	this.instance_4.setTransform(148.45,72.25);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.instance_3}]},17).to({state:[{t:this.instance_4}]},6).wait(56));
	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(17).to({_off:false},0).to({_off:true,y:72.25,alpha:1},6).wait(56));

	// Layer_5
	this.instance_5 = new lib.Tween7("synched",0);
	this.instance_5.parent = this;
	this.instance_5.setTransform(148.45,85.35);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.instance_6 = new lib.Tween8("synched",0);
	this.instance_6.parent = this;
	this.instance_6.setTransform(148.45,160.35);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.instance_5}]},33).to({state:[{t:this.instance_6}]},9).to({state:[{t:this.instance_6}]},36).wait(1));
	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(33).to({_off:false},0).to({_off:true,y:160.35,alpha:1},9).wait(37));

	// Layer_1
	this.instance_7 = new lib.bg_300x600_2();
	this.instance_7.parent = this;
	this.instance_7.setTransform(0,-1);

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(79));

	// BG
	this.instance_8 = new lib.bg_300x600();
	this.instance_8.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(79));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(150,-321,243.89999999999998,921);
// library properties:
lib.properties = {
	id: '518BD99F26E84AE1902D4F543675FC66',
	width: 300,
	height: 600,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/snow.png", id:"snow"},
		{src:"images/300x600_atlas_P_.png", id:"300x600_atlas_P_"},
		{src:"images/300x600_atlas_NP_.jpg", id:"300x600_atlas_NP_"},
		{src:"images/300x600_atlas_NP_2.jpg", id:"300x600_atlas_NP_2"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['518BD99F26E84AE1902D4F543675FC66'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}			
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;			
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});			
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;			
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;